### ISSUE TITLE
Does OpenSCAD Docker have a rest api?

### ISSUE THREAD

**Issue by devbyray** [openscad/docker-openscad#20]
I love using OpenSCAD ❤️!

I try to figure out what practical use this thing has 😅. As a developer, I expected it would expose an API that could render my scad files so I could show a visual in my browser with a custom frontend.

But I can't find anything about an API. 

Can you please explain it to me?

**Comment by thehans** [comment]
There is no REST API because OpenSCAD is not a webservice.  

The first lines of the readme explains the usage of this repo

> This repository collects OpenSCAD related docker files. One is meant for running OpenSCAD in a container (for building models, etc.), while the rest are meant for internal use in the OpenSCAD CI automation.

**Comment by t-paul** [comment]
@devbyray maybe the WASM version would be worth a look. It does not have an API either, but could run directly in the browser like on the openscad-playground page: https://ochafik.com/openscad2/
