### ISSUE TITLE
Official builds work but dev snapshots are broken for a long time.

### ISSUE THREAD

**Issue by praetp** [openscad/docker-openscad#21]
```
$ docker run openscad/openscad:dev.2024-05-13 --help
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--help": executable file not found in $PATH: unknown.
```
I tried some from January but got the same error.

The instructions from this website (using the official builds) do work.

**Comment by t-paul** [comment]
That command line can't work, it tries to start a program called `--help` causing the error message.

The dev snapshot is fine, for some examples, see: https://hub.docker.com/r/openscad/openscad

```
echo 'difference() { cube(12, center=true); #sphere(8); }' > test.scad

docker run --rm -v $(pwd):/openscad openscad/openscad:dev.2024-05-13 openscad -o test.png test.scad

eog test.png
```
<img src="https://github.com/openscad/docker-openscad/assets/1330241/b6aaa7a3-94a4-4785-9e3e-1d69a9e869d6" width="300">
