### ISSUE TITLE
Official docker image for building openscad files?

### ISSUE THREAD

**Issue by kasbah** [openscad/docker-openscad#3]
We use [Gitlab CI to build](https://gitlab.com/openflexure/openflexure-microscope/-/blob/master/.gitlab-ci.yml) the STLs for our [microscope and other designs](https://openflexure.org/). Would be handy if we could just pull in a base image with an up-to-date OpenSCAD (`openscad/openscad:latest` ?) instead of that dance with Ubuntu and the PPA. What do you think?

**Comment by t-paul** [comment]
Ah, nice. See discussion in #2, would that change already cover what you need for the CI?

**Comment by kasbah** [comment]
I am not sure, sorry. I don't understand those changes. 

We just want to be able to say `image: openscad/openscad:latest` in our CI config and use that for our builds. Maybe something similar is already possible and I just don't know about it?

I guess it's less important for us since we already set up a working CI, but for new projects that want to set up OpenSCAD builds in CI, that way would be much simpler than figuring out how to get an up-to-date OpenSCAD into another image. 

(We'd also need to install Python alongside OpenSCAD but I assume that will be less fuss.)

**Comment by t-paul** [comment]
Well, it's just unfortunate that OpenSCAD fell out of Ubuntu 18.04 for totally Ubuntu unrelated reasons. It should be back in 20.04 (unfortunately we'll likely miss the deadline for getting a new release out, but 2019.05 should be there). So the normal expectation is to be able to just use `apt-get install openscad`. I've not tested it, but OpenSCAD is also available in the Alpine package repo for minimal image sizes.

That said, maybe having a separate base image might be still useful with tags for releases and `:nightly` tracking master branch builds. I'm not sure what the best base image would be, but I suspect latest Ubuntu LTS is probably the way to go.

**Comment by kasbah** [comment]
Sure, if you can just `apt install` that makes it easier too. I think having an "official" openscad docker image for based on alpine would still be cool. People with a little familiarity with docker will know exactly what to do with it.

**Comment by dimo414** [comment]
Official user-facing Docker images would be great, I came across this repo and the images in https://hub.docker.com/u/openscad (by Googling [docker openscad], of course) looking for an image I could just run with.

It'd also be helpful to document in Docker Hub and the README here the purpose of these images, since I spent a few minutes trying to figure it out.

**Comment by spuder** [comment]
I also would like to be able to run `docker run openscad/openscad:latest` in a CI System. 

Do none of these images provide a working openscad binary? 
https://hub.docker.com/u/openscad

❌ = [mxe-x86_64-gui](https://github.com/openscad/docker-openscad/blob/master/mxe/mxe-x86_64-gui/Dockerfile) (not sure what this does?)
❌ = [mxe-x86_64-openscad](https://github.com/openscad/docker-openscad/blob/master/mxe/mxe-x86_64-openscad/Dockerfile) (creates a tarball)
❌  = [appimage-x86_64-base](https://github.com/openscad/docker-openscad/blob/master/appimage/appimage-x86_64-base/Dockerfile) (creates /appimage directory but there are no working binaries in that folder)
🟢   = [appimage-x86_64-openscad](https://github.com/openscad/docker-openscad/blob/master/appimage/appimage-x86_64-openscad/Dockerfile) (creates a tarball ,this _could_ be modified to work with a modified entrypoint [as shown here](https://github.com/openscad/docker-openscad/pull/2/files
); however it appears that only the arm builds got pushed to dockerhub, no intel builds got pushed. 😢  )

**Comment by t-paul** [comment]
No, those images are still only meant for the [OpenSCAD CI Pipeline](https://github.com/openscad/openscad/wiki/CI-Setup). I'd like that to change at some point, but without help that may or may not happen in the near future.

**Comment by spuder** [comment]
Thank you. I will look into how much work it would be and try and see if I am able to contribute. 

For anyone else looking to create an openscad image, you could try making your own docker container. 
```
FROM ubuntu:20.04
RUN apt update && apt install -y openscad
```
```
docker build . -t foobar/openscad
```

Unfortunately the latest version of openscad in ubuntu repos is `2019.05`
```
openscad --version
OpenSCAD version 2019.05
```

**Comment by spuder** [comment]
I've built my own openscad containers that work for my pipelines

```
docker pull spuder/openscad:latest
```

Documentation is available in this repo https://github.com/spuder/openscad-dockerhub

It is based off of the 2021.01 release running on official debian docker container

**Comment by t-paul** [comment]
Images of 2019.05 and 2021.01 based on Debian Buster and dev snapshot based on Debian Bookworm are now available at:

https://hub.docker.com/repository/docker/openscad/openscad
