### ISSUE TITLE
Release images for Apple M1 / ARM

### ISSUE THREAD

**Issue by spuder** [openscad/docker-openscad#8]
If you attempt to run these docker containers on an Apple M1 Processor, you get the following error

```
docker run openscad/openscad:2021.01 openscad version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

## Solutions

1. Use buildx [as shown in this blog](https://www.docker.com/blog/multi-arch-images/)

Pros: Just works
Cons: Requires docker desktop which is now a paid product if running on a work computer

2. Offload building ci images from developer workstation to github actions. [Here is an example](https://github.com/spuder/stl2origin/blob/master/.github/workflows/dockerhub.yaml#L33)

**Comment by t-paul** [comment]
Looks like `docker buildx` is still supported on CE. Latest release and dev snapshot are now available for both `arm64` and `amd64` platforms. Tested on Raspberry PI 400.

Older releases may or may not follow, if it just works, they'll appear in the near future.

If this works specifically for Apple M1, I can't test, so I'm going to close this as solved. There's not going to be dedicated M1 support for docker images at this point.

**Comment by t-paul** [comment]
FWIW, all images are now available for both architectures: https://hub.docker.com/r/openscad/openscad/tags

**Comment by spuder** [comment]
Thank you. Tested and is working on M1 Mac

```
docker run --init openscad/openscad:2021.01 xvfb-run -a openscad --version
OpenSCAD version 2021.01
```

**Comment by t-paul** [comment]
Thanks, that's very good news.

**Comment by spuder** [comment]
For future reference here was the solution. ( I find myself referring back to this issue frequently) 

https://github.com/openscad/docker-openscad/commit/77233956de3030b0a1e351056f14aae84b6af1e4

```
	docker buildx build \
		--push \
		--platform linux/amd64,linux/arm64 \
		--build-arg=REFS="$REF" \
		--build-arg=BRANCH="$BRANCH" \
		--build-arg OPENSCAD_VERSION="$VERSION" \
		--build-arg BUILD_TYPE="Release" \
		--build-arg DEBUG="-" \
		--build-arg JOBS=4 \
		$DOCKERTAG1_ARGS \
		$DOCKERTAG2_ARGS \
		$DOCKERFILE_ARGS \
		"$DIR"
```
